urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from . import views

app_name = "EFM"
urlpatterns = [
    # /efm/ - overview
    path('', views.indexView.as_view(), name='index'),
    path('tree/<int:pk>/', views.efmTreeView.as_view(), name='treeView'),
    path('fr/<int:pk>/', views.frDetail.as_view(), name='frDetail'),
    path('ds/<int:pk>/', views.dsDetail.as_view(), name='dsDetail'),
    path('ds/', views.dsDetail.as_view(), name='dsSlot'),
    path('fr/', views.frDetail.as_view(), name='frSlot'),
    url(r'^ds/(?P<pk>\d+)/newFR/', views.fr_new, name='newFR'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

models.py
from django.db import models
import uuid
# Create your models here.
## CHECKUP FOREIGN KEYS on inherited models!!!!!

class boxObject(models.Model):
    ''' master object for all DS, Fr and C '''
    type="object"
    name = models.CharField(max_length=200)
    #shortHand = models.CharField(max_length=100, unique=True, default = "{}-{}".format(type, str(id)) )
    description = models.TextField(blank=True)
    class Meta:
        abstract = True
    
    def __str__(self):
        return self.name
    
class ds(boxObject):
    #isb = models.ForeignKey('fr', on_delete=models.CASCADE, blank=True)
    isb = models.OneToOneField('fr', on_delete=models.CASCADE, null=True)
    image = models.FileField(upload_to='ds_images', null=True, blank=True) 
    type="ds"

    
class fr(boxObject):
    rf = models.ForeignKey('ds', on_delete=models.CASCADE, null=True, blank=True)
    type="fr"
       

class parameter(models.Model):
    ''' 
    Master class for all parameters in an object 
    if possible should also be used in DR elements
    needs to be equipped with evaluation and mathematical functions later!
    '''
    
    object = models.ForeignKey('boxObject', on_delete=models.CASCADE)
    
    name = models.CharField(max_length=200)
    value = models.CharField(max_length=200, blank=True)
    
    def __str__(self):
        return (self.name) 
        
    class Meta:
        abstract = True

class dsParameter(parameter):
    object = models.ForeignKey(ds, on_delete=models.CASCADE)
class frParameter(parameter):
    object = models.ForeignKey(fr, on_delete=models.CASCADE)

forms.py
from django import forms
from .models import fr

class frForm(forms.ModelForm):
    
    class Meta:
        model = fr
        fields = ('name', 'description')

views.py
from django.shortcuts import render, redirect
from django.views import generic

from .models import fr, ds
from .forms import frForm
# Create your views here.

class indexView(generic.ListView):
    template_name = "efm/overview.html"
    context_object_name = "topLvlFr"
    model = fr
    
        
class efmTreeView(generic.DetailView):
    model = fr
    template_name = 'efm/efmView.html' 
    
class frDetail(generic.DetailView):
    model = fr
    template_name = "efm/frDetail.html"    
    
class dsDetail(generic.DetailView):
    model = ds
    template_name = "efm/dsDetail.html"
    
def fr_new(request, pk):
    if request.method == "POST":
        form = frForm(request.POST)
        if form.is_valid():
            newFR = form.save(commit=False)
            parentID = int(request.POST.get("rf", ""))
            newFR.rf = ds.objects.get(pk=parentID)
            newFR.save()
            return redirect('EFM:treeView', pk= parentID)
    else:
        form = frForm()
        parent = ds.objects.get(pk=pk)
    return render(request, 'efm/newFR.html', {'form': form, 'parent': parent,})

templates/EFM/dsDetail.html
<div>
    <h2 id="objTitle"> DS: {{ds.name}} </h2>
    <p id="objDesc"> {{ds.description}}</p>
    <a href="{% url 'EFM:newFR' ds.id %}" title="New FR">[+]</a>
    <div class="newFRbutton" id="newFR{{ds.id}}">[+add]</div>
    <p> <h3>fulfills fr: </h3> {{ds.isb.name}}</p>
    <p>
    <h3> requires the functions: </h3>
        <ul>
        {% for f in ds.fr_set.all %}
            <li>{{f.name}}</li>
        {% empty %}
            <li> NO FR </li>
        {% endfor %}
        </ul>
    </p>
</div>

templates/EFM/efmView.html
{% extends "efm/frame.html" %}

{% block title %}
{{fr.name}}
{% endblock %}

{% block mainContent %}
<div class="efmTree">
    <div class="frTree">
        {% include  "efm/treeview.html" %}
    </div>
</div>

<div id="closeDetailsCanvas">&lt;</br>&gt;</div>

<div id="detailsCanvas">
    <h2> click on an object for details </h2>
    {% comment %}
    <h2 id="objTitle"> {{fr.name}} </h2>
    <p id="objDesc"> {{fr.description}}</p>
    <a href="{% url 'EFM:newFR' %}" title="New FR">[+]</a>
    <p> <h3>parent: </h3> {{fr.rf.name}}</p>
    <p>
    <h3> children: </h3>
        <ul>
        {% for d in fr.ds %}
            <li>d.name</li>
        {% empty %}
            <li> no child-nodes </li>
        {% endfor %}
        </ul>
    </p>
    {% endcomment %}
    
</div>
    
{% endblock %}

{% block javascript %}

$("#closeDetailsCanvas").click(function(){
   $("#detailsCanvas").toggle("slide");
});

// click on DS element
$(".ds").click(function() {
    // getting ID and removing 2 first digits ("ds")
    var id = event.target.id;
    id = id.substring(2)
    
    // highlighting the div via class assignment
    $(".highlight").removeClass("highlight")
    $(this).addClass("highlight")
    
    // loading the respective info into the sidebar:
    $("#detailsCanvas").html('&nbsp;').load('{% url  'EFM:dsSlot' %}' + id + '/');
    
});

//click on FR element
$(".fr").click(function() {
    // getting ID and removing 2 first digits ("fr")
    var id = event.target.id;
    id = id.substring(2);
    
    // highlighting the div via class assignment
    $(".highlight").removeClass("highlight");
    $(this).addClass("highlight");
    
    // loading the respective info into the sidebar:
    $("#detailsCanvas").html('&nbsp;').load('{% url  'EFM:frSlot' %}' + id + '/');
});

$(document).on("click", '.newFRbutton', function() {
    var dsID = this.id.substring(5);
    var dsIDdom = "#ds".concat(dsID);
    var dsContainer = $(dsIDdom).parent()
    var frHTML = "<div class='frTree'>  \
    <svg class='rf' height='1000' width='15'><text x='5' y='35' fill='black'>rf</text>  \
    <line x1='5' y1='0' x2='5' y2='40' style='stroke:rgb(0,0,0);stroke-width:2' />  \
    <line x1='5' y1='40' x2='15' y2='40' style='stroke:rgb(0,0,0);stroke-width:2' />  \
    <div class='fr' id='fr{{fr.id}}'> <h2> FR </h2>TEST TEST</div>  \
    </div>";
    $(dsContainer).append(frHTML);
});



{% endblock %}

templates/EFM/frDetail.html
<div>
    <h2 id="objTitle"> FR: {{fr.name}} </h2>
    <p id="objDesc"> {{fr.description}}</p>
    <a href="">[+]</a>
    <p> <h3>is required by: </h3> {{fr.rf.name}}</p>
    <p><h3> is solved by: </h3> {{ fr.ds}}</p>
</div>

templates/EFM/fr_edit.html
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">save</button>
</form>

templates/EFM/frame.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href={% static 'EFM/css/main.css' %}>
<title>{% block title %} an efm tree {% endblock %} </title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</head>

<body>
<div class="flexBox">
    <div class="header">
        <h1> Chalmers Function Modeller </h1>
    </div>
    
    <div class="mainArea">
    
        {% block mainContent %}
        no data to load
        {% endblock %}
    
    </div>
    
</div>
<script>
{% block javascript %}
{% endblock %}
</script>    
</body>

</html>

templates/EFM/newFR.html
{{parent.name}} - {{parent.pk}}
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="hidden" name="rf" value="{{parent.pk}}">
    <button type="submit">save</button>
</form>

templates/EFM/overview.html
{% extends "efm/frame.html" %}

{% block title %}
Overview
{% endblock %}

{% block mainContent %}

<h1> all the top-level-fr: </h1>

<ul>
    {% for fr in object_list %}
        <li><a href="{% url 'EFM:treeView' fr.id %}">{{ fr.name }}</a></li>
    {% empty %}
        <li>No articles yet.</li>
    {% endfor %}

</ul>
{% endblock %}

templates/EFM/treeview.html
{# top-node FR: #}
<div class="fr" id="fr{{fr.id}}"> <h2> FR </h2>
    {{ fr.name }}           
</div>
{# each DS gets a "DS-container" aka dsTree: #}
<div class="dsTree">
{% if fr.ds %}
    <svg class="isb" height="80" width="15">
        <text x="0" y="35" fill="black">isb</text>
        <line x1="0" y1="40" x2="15" y2="40" style="stroke:rgb(0,0,0);stroke-width:2" />
    </svg>
    <div class="ds" id="ds{{fr.ds.pk}}">  <h2>DS</h2>
        {{ fr.ds.name }}  
    </div>
            
        {% for req in fr.ds.fr_set.all %}
        
            {% with fr=req temp_name='EFM/treeview.html' %}
                <div class="frTree">
                
                    <svg class="rf" height="1000" width="15">
                        <text x="5" y="35" fill="black">rf</text>
                        {% if forloop.first %}
                            {# vertical line down and full horizontal line #}
                        <line class="vertiBottom" x1="5" y1="40" x2="5" y2="1000" style="stroke:rgb(0,0,0);stroke-width:2" />
                        <line class="horiLong" x1="0" y1="40" x2="15" y2="40" style="stroke:rgb(0,0,0);stroke-width:2" />
                        {% elif forloop.last %}
                            {# short vertical line #}
                        <line  class="vertiTop"x1="5" y1="0" x2="5" y2="40" style="stroke:rgb(0,0,0);stroke-width:2" />
                        <line class="horiShort" x1="5" y1="40" x2="15" y2="40" style="stroke:rgb(0,0,0);stroke-width:2" />
                        {% else %}
                            {# full vertical line #}
                        <line class="vertiFull" x1="5" y1="0" x2="5" y2="1000" style="stroke:rgb(0,0,0);stroke-width:2" />
                        <line class="horiShort" x1="5" y1="40" x2="15" y2="40" style="stroke:rgb(0,0,0);stroke-width:2" />
                        {% endif %}
                    </svg>
                    
                    {% include  temp_name %}
                </div>
                
            {% endwith %}   
            
        {% endfor %}
{% endif %}
</div>